
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (yy_size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[362] =
    {   0,
        2,    2,    0,    0,    0,    0,   64,   62,    2,    1,
       59,   13,   62,   59,   59,   62,   59,   59,   60,   59,
       20,   59,   19,   61,   59,   62,   59,   56,   20,   59,
       62,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   62,    2,   56,
       56,   56,   56,   56,   56,   56,   56,    8,    9,    8,
        8,   18,   17,   16,   63,    2,   59,    0,    0,    0,
        0,   11,   58,   20,   20,    6,   12,   20,   19,   56,
       56,    0,    0,   21,   20,   20,   20,   21,   21,   21,
       56,   56,   56,   56,   56,   56,   31,   56,   56,   56,

       56,   56,   56,   39,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,    2,    0,    0,
        0,    0,    0,    0,    0,    0,   56,   31,   56,   56,
       56,   56,   56,   56,   56,   10,    7,   15,   14,   15,
        0,   22,   58,   20,   12,    0,   57,    0,    0,   20,
       20,   20,   20,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   37,   56,   40,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   56,   56,   56,   40,   56,   56,   56,

       56,   56,    0,   24,   56,   26,   27,   56,   56,   56,
       56,   33,   34,   56,   56,   38,   41,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       53,   56,   56,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   27,   56,   56,    0,   41,   56,   56,   56,
       53,    0,   25,   28,   56,   56,   56,   56,   36,   56,
       56,   56,    5,   44,   56,   56,   56,   56,   56,   56,
       51,   56,   56,   55,    0,    0,    0,    0,    0,   56,
       36,    0,   44,   56,   56,    0,   56,   56,   32,   35,
        4,   56,   43,   45,   46,   47,   48,   49,   56,   56,

       56,    0,    0,    0,   32,    0,    0,    0,   45,   56,
        0,   56,   30,   56,   50,   56,   56,    0,    0,    0,
       23,   56,   56,   56,   56,   56,   56,   56,   56,    0,
       29,   42,   52,   54,    0,    0,   23,   56,   56,   56,
       56,   56,   56,   56,   52,    0,    0,   56,   56,   56,
       56,   56,   56,   56,    0,   56,   56,   56,    3,   56,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   25,   41,   42,   43,   44,
       45,   46,   25,   47,   48,   49,   50,   51,   52,   53,
       54,   55,    1,   56,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[57] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        5,    1,    6,    1,    1,    1,    1,    6,    7,    1,
        1,    6,    8,    1,    9,    9,   10,    1,    1,    1,
       11,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    1
    } ;

static yyconst flex_int16_t yy_base[376] =
    {   0,
        0,   55,   55,   57,   58,   59,  672, 1385,   65, 1385,
      638, 1385,  619,  627,   54,    0,   78,   52, 1385,   55,
       53,   80,   82, 1385,  625,  624,  611,   85,  116, 1385,
      606,  154,  155,  156,   49,  152,  161,  175,  171,  177,
      178,  194,  195,  204,  136,  206,  209,   58,  257,  584,
      221,  223,  227,  231,   44,  230,  243, 1385, 1385,  604,
      601, 1385, 1385, 1385,  303,  105, 1385,  567,  590,  224,
      280, 1385,    0,  173,  287, 1385,    0,  192,  260,  278,
      279,  202,  254, 1385,   94,  580,  295,  301,  271,  302,
      311,  322,  336,  312,  295,  324,  320,  327,  332,  337,

      333,  355,  356,  359,  364,  355,  370,  373,  386,  388,
      396,  397,  398,  400,  408,  410,  415,    0,  559,  552,
      552,  545,  538,  137,  527,  524,  426,  428,  430,  438,
      432,  447,  450,  458,  460, 1385, 1385, 1385, 1385,  508,
      524, 1385,    0,  233,    0,  296, 1385,  453,  480,  535,
      270,  534,  493,  476,  477,  494,  499,  517,  503,  528,
      536,  531,  546,  545,  547,  548,  556,  564,  475,  564,
      563,  481,  568,  576,  583,  582,  588,  595,  598,  611,
      613,  622,  623,  621,  519,  500,  502,  494,  493,  484,
      489,  453,  441,  622,  637,  639,  678,  653,  654,  652,

      660,  653,  419,  665,  678,  672,  682,  685,  688,  695,
      698,  702,  705,  710,  717,  718,  723,  730,  733,  738,
      750,  746,  760,  644,  761,  773,  776,  676,  767,  781,
      780,  786,  796,  402,  391,  384,  417,  369,  346,  348,
      343,  321,  812,  799,  802,  462,  825,  815,  830,  833,
      843,  296,  837,  838,  850,  851,  863,  856,  864,  876,
      870,  880,  883,  884,  896,  897,  901,  902,  711,  920,
      831,  916,  922,  919,  303,  285,  270,  280,  258,  932,
      969,  975,  976,  946,  940,  232,  945,  952,  962,  966,
      970,  988,  983,  984,  989,  996, 1001, 1002, 1014, 1017,

     1018,  220,  197,  175, 1046,  998,  200, 1061, 1066, 1032,
      162, 1033, 1036, 1040, 1039, 1060, 1076, 1088,  154,  167,
      489, 1034, 1066, 1082, 1089, 1095, 1105, 1106, 1114,  274,
     1109, 1123, 1124, 1125,   80,   80,  492, 1126, 1128, 1140,
     1142, 1133, 1144, 1156,    0,  385,    0, 1158, 1161, 1170,
     1178, 1175, 1179, 1190,   87, 1177, 1189, 1190, 1385, 1204,
     1385, 1257, 1268, 1279, 1287, 1292, 1303, 1308, 1317, 1328,
     1333, 1343, 1353, 1362, 1373
    } ;

static yyconst flex_int16_t yy_def[376] =
    {   0,
      361,    1,  362,  362,  363,  363,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  364,  365,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  366,  361,  361,
      361,  366,  366,  366,   34,   34,   34,   34,   36,   34,
       34,   34,   34,   34,   36,   34,   34,  361,  361,   34,
       34,   34,   36,   34,   43,   36,   34,  361,  361,  361,
      361,  361,  361,  361,  367,  361,  361,  361,  361,  365,
      365,  361,  368,  361,  369,  361,  370,  361,  361,   34,
       34,  361,  371,  361,  361,  361,  366,  366,  361,  371,
      366,  366,  366,   34,   36,   36,   36,   36,   36,   36,

       34,   34,   34,   34,   34,   36,   36,   36,   34,   34,
       34,   34,   34,   34,   34,   36,   36,   49,  361,  361,
      361,  361,  361,  361,  361,  361,   34,   34,   34,   34,
       36,   34,   34,   34,   36,  361,  361,  361,  361,  367,
      361,  361,  368,  361,  370,  361,  361,  371,  371,  361,
      361,  361,  366,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   34,
       34,   34,   34,   36,  361,  361,  361,  361,  361,  361,
      361,  361,  361,   36,   36,   34,   34,   34,   34,   36,

       36,   36,  361,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   34,   34,   34,   34,   34,   36,   36,
       36,   36,   36,  361,  361,  361,  361,  361,  361,  361,
      361,  361,   36,   36,   36,  372,   36,   36,   36,   36,
       36,  361,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   34,   34,
       34,   36,   36,   36,  361,  361,  361,  361,  361,   36,
       36,  373,   36,   36,   36,  361,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,  361,  361,  361,   36,  361,  374,  373,   36,   36,
      361,   36,   36,   36,   36,   36,   36,  361,  361,  374,
      361,   34,   34,   36,   36,   34,   34,   34,   34,  361,
       34,   34,   34,   34,  361,  361,  361,   34,   34,   34,
       34,   36,   34,   34,  309,  361,  375,   34,   34,   34,
       34,   34,   34,   34,  375,   36,   36,   36,  361,   36,
        0,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361
    } ;

static yyconst flex_int16_t yy_nxt[1442] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
        8,    8,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    8,   28,   29,   30,    8,   30,   31,
       28,   32,   33,   34,   35,   36,   37,   38,   28,   39,
       28,   40,   28,   28,   28,   41,   42,   43,   44,   45,
       46,   47,   28,   28,   28,   48,   49,   59,   49,   59,
       63,   63,   67,   64,   64,   67,   66,   60,   66,   60,
       67,   74,   61,   67,   61,   67,   67,   67,   75,   67,
       81,   70,  132,  133,   96,   65,   65,   81,   50,   51,
       71,   52,   76,   97,   53,   72,   54,   77,   78,   67,

       79,   67,   55,   80,   56,   57,   66,   75,   66,  359,
      150,   82,  151,   67,  318,   83,   84,   84,  190,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   85,
       84,   85,   86,   84,   87,   84,   84,   84,   84,   84,
       88,   88,   89,   84,   84,   84,   90,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   85,   80,   80,   80,  190,  191,   81,  321,  115,
       82,   82,   82,   81,   83,   83,   83,   93,   81,  336,
       81,   74,   81,   98,   94,   99,   81,  330,   75,   81,

       95,   92,  101,   91,  100,  102,   81,  104,   81,   81,
       74,  321,   81,   81,  105,   81,   81,   75,  319,  103,
      146,  106,   81,   81,  107,   81,   81,   70,  109,  108,
      147,  318,   81,  110,  111,   81,  361,   81,   81,   81,
       81,  361,   81,  112,   81,  361,  113,  117,   81,  150,
      116,  151,   81,   81,   81,  237,   96,  114,  118,   81,
      118,   81,   81,  104,  129,  128,  311,  102,   81,   81,
      130,   81,  148,  134,   81,  131,   78,  346,   79,   81,
       82,   81,   81,   70,   83,   75,  150,  135,  151,  146,
      119,  120,   71,  121,  347,  304,  122,  361,  123,  147,

       85,  361,   85,   86,  124,  144,  125,  126,  139,   81,
       81,  150,  139,  153,  146,  303,   81,   81,  237,   80,
      148,   82,   81,   81,  147,   83,  139,   82,   82,   80,
      140,   83,   83,  237,  139,  139,   81,   82,  158,  139,
       80,   83,   85,  157,  302,  286,  139,   81,   82,  139,
       81,  139,   83,  139,   80,  237,   81,  155,  139,  154,
      159,   81,   82,   81,   81,   81,   83,   81,   81,  160,
       81,   81,   81,   81,  161,   81,   81,  164,   81,   81,
       81,  162,  279,  156,   81,  163,   81,   81,  346,   81,
       81,  278,  277,   81,   81,   81,   81,   81,  168,   81,

       81,  165,   81,   81,  166,  347,  237,   81,   81,  169,
      170,   81,  167,   81,   81,  276,   81,  172,  246,   81,
      246,  171,   81,  275,   81,   81,   81,   81,  176,   81,
       81,   81,  173,  174,   81,   81,   81,  178,   81,   81,
       81,   81,   81,  177,   81,  179,   81,  180,  237,  182,
      175,  183,   81,   81,  184,  181,   81,  194,   81,   81,
      252,   81,   81,  246,   81,  246,   81,   81,   81,   81,
       81,  148,   81,   81,  196,  198,   81,  195,   81,   82,
      242,   81,   81,   83,   81,   81,  197,  200,   81,   81,
      337,  199,  337,  337,   81,  337,   81,  180,  148,  202,

      241,  183,   81,   81,  175,  201,   82,   81,  205,  150,
       83,  153,   81,  139,   81,   81,   81,  139,  218,   82,
      204,   81,   81,   83,  221,   81,  240,   81,  239,  206,
       81,  139,   81,   81,  210,  140,  238,   81,   81,  139,
      139,   81,  237,   81,  139,  207,  236,   81,   81,  235,
      234,  139,  152,  152,  139,   81,  139,  203,  139,   81,
      211,   81,   81,  139,  208,  209,   81,   81,  193,   81,
      192,  212,   81,  213,   81,   81,  215,   81,   81,   81,
       81,  214,  189,   81,   81,   81,   81,   81,  188,   81,
       81,   81,  216,  187,   81,   81,  186,  185,  152,  142,

       81,  217,   81,  219,   81,   81,   81,   81,   81,   81,
      141,   81,  220,  137,  222,   81,   81,   81,  224,  223,
       81,  136,  127,   81,   81,   81,   81,   67,   81,   81,
      225,   81,   67,  228,   81,   81,   81,  226,   81,   81,
       81,   81,   81,  227,   81,   67,   67,   81,   67,   81,
       81,   81,  230,   81,  232,  229,  231,   81,   68,   67,
       81,   81,  233,   81,   81,   81,   81,   81,  243,  244,
      245,  361,  361,   81,   81,   81,  361,   81,   81,  246,
       81,  246,   81,   81,   81,   81,  361,  251,  266,   81,
      247,   81,   81,   81,   81,  249,   81,   81,   81,  250,

      248,   81,  361,   81,   81,   81,   81,   81,   81,   81,
      270,  361,   81,   81,   81,   81,   81,   81,  253,   81,
       81,   81,   81,   81,   81,   81,   81,  255,   81,   81,
       81,   81,  361,  254,   81,  361,   81,   81,   81,  257,
       81,   81,   81,   81,  256,   81,   81,   81,   81,  298,
       81,   81,  361,   81,   81,   81,  258,   81,   81,   81,
       81,   81,   81,  361,   81,  259,   81,  361,  361,   81,
       81,   81,  361,   81,   81,   81,   81,  361,  260,   81,
      261,   81,   81,  361,  262,   81,  263,   81,  361,   81,
       81,   81,   81,   81,  264,  265,  361,  361,   81,   81,

      267,   81,   81,   81,   81,   81,  268,   81,   81,  269,
      271,   81,   81,  246,   81,  246,  361,   81,  272,   81,
       81,   81,   81,   81,   81,  361,  246,   81,  246,   81,
      361,  274,   81,   81,  273,  361,  361,   81,   81,   81,
      280,  361,   81,   81,  246,   81,  246,  361,   81,  361,
      281,   81,  361,   81,   81,   81,   81,  361,   81,  361,
      361,  361,   81,  283,   81,  284,   81,   81,   81,   81,
      285,   81,  361,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,  361,   81,   81,   81,  361,  361,   81,
       81,   81,  288,  287,   81,   81,  361,   81,  289,  290,

      361,  361,   81,   81,   81,   81,   81,   81,   81,  361,
      361,   81,  291,   81,  361,   81,   81,   81,  292,   81,
      361,   81,   81,  293,   81,   81,   81,   81,   81,  361,
      294,  361,   81,  295,  296,   81,   81,   81,   81,   81,
       81,  361,   81,   81,   81,   81,  361,  361,   81,   81,
      297,   81,  361,   81,   81,  299,  361,   81,   81,  300,
       81,  301,   81,   81,   81,   81,  361,  305,   81,  361,
      246,   81,  246,   81,   81,   81,  306,  246,  306,  246,
      309,   81,  361,  310,   81,  307,   81,   81,   81,   81,
      361,  361,   81,   81,  312,   81,  361,   81,   81,  306,

      313,  306,  361,   81,   81,   81,  361,   81,  307,   81,
       81,   81,   81,   81,   81,  361,  361,   81,   81,   81,
      361,   81,   81,  314,   81,   81,   81,   81,   81,   81,
       81,   81,   81,  361,  361,   81,   81,   81,  361,   81,
       81,   81,   81,   81,   81,   81,  361,  246,   81,  246,
      315,  361,  316,   81,   81,   81,  361,   81,   81,  317,
       81,   81,  306,  361,  306,   81,   81,  329,  331,   81,
       81,  307,  338,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,  332,   81,   81,   81,
      361,   81,   81,  361,  333,  361,  361,   81,   81,  322,

      323,   81,  324,   81,   81,  325,  361,  326,  361,   81,
      339,  334,   81,  327,  361,  361,  328,   81,   81,   81,
      361,  119,  120,  340,  121,   81,   81,  122,   81,  123,
       81,  361,  341,   81,   81,  335,   81,   81,  126,  342,
       81,   81,  361,  343,   81,   81,  361,   81,  345,   81,
      344,  361,   81,   81,   81,   81,   81,  348,   81,   81,
      361,   81,   81,   81,   81,  361,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,  352,  349,   81,  246,
       81,  246,   81,  361,  350,   81,   81,   81,  353,   81,
      351,  361,   81,  356,   81,  354,   81,  361,  361,   81,

       81,  357,   81,  361,  351,   81,   81,  361,   81,   81,
       81,  361,  351,   81,   81,  361,   81,   81,  360,   81,
       81,   81,   81,   81,  351,  358,  361,  361,   81,   81,
       81,   81,   81,   81,   81,  361,  361,  351,  351,  351,
      361,   81,   81,  361,  361,   81,  361,   81,  361,  361,
      361,  361,  361,  361,  361,  361,   81,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   69,
       69,  361,   69,   69,   69,   69,   69,   69,   69,   69,
       73,  361,   73,  361,  361,   73,  361,   73,   81,  361,

       81,   81,   81,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  143,  361,  143,   84,   84,  361,
       84,   84,   84,   84,   84,   84,   84,   84,  145,  145,
      361,  145,  145,  145,  145,  145,  145,  145,  145,  149,
      361,  149,  149,  149,  282,  361,  282,  361,  361,  361,
      361,  282,  361,  282,  308,  361,  308,  308,  361,  308,
      361,  308,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  355,  355,  355,  355,  355,  355,  355,
      361,  355,  355,  355,    7,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,

      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361
    } ;

static yyconst flex_int16_t yy_chk[1442] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    3,    2,    4,
        5,    6,   15,    5,    6,   18,    9,    3,    9,    4,
       20,   21,    3,   18,    4,   15,   20,   20,   21,   48,
       35,   17,   55,   55,   35,    5,    6,   35,    2,    2,
       17,    2,   22,   35,    2,   17,    2,   22,   23,   17,

       23,   22,    2,   28,    2,    2,   66,   23,   66,  355,
       85,   28,   85,   48,  336,   28,   29,   29,  335,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   32,   33,   34,  124,  124,   45,  320,   45,
       32,   33,   34,   36,   32,   33,   34,   34,   45,  319,
       36,   74,   37,   36,   34,   36,   36,  311,   74,   37,

       34,   33,   37,   32,   36,   37,   38,   39,   40,   41,
       78,  307,   39,   38,   39,   40,   41,   78,  304,   38,
       82,   40,   41,   39,   41,   42,   43,   70,   43,   42,
       82,  303,   42,   43,   43,   44,   70,   46,   42,   43,
       47,   70,   44,   43,   46,   70,   43,   47,   44,  144,
       46,  144,   51,   47,   52,  302,   51,   44,   49,   51,
       49,   52,   54,   53,   52,   51,  286,   52,   53,   54,
       53,   56,   83,   56,   57,   54,   79,  330,   79,   53,
       83,   57,   56,   71,   83,   79,  151,   57,  151,   89,
       49,   49,   71,   49,  330,  279,   49,   71,   49,   89,

       75,   71,   75,   75,   49,   75,   49,   49,   65,   80,
       81,   87,   65,   87,  146,  278,   80,   81,  277,   88,
       90,   87,   80,   81,  146,   87,   65,   88,   90,   91,
       65,   88,   90,  276,   65,   65,   95,   91,   95,   65,
       92,   91,   75,   94,  275,  252,   65,   95,   92,   65,
       94,   65,   92,   65,   93,  242,   94,   92,   65,   91,
       96,   97,   93,   97,  101,   96,   93,   96,   98,   97,
       98,  101,   97,   99,   98,   99,   96,  101,  100,   98,
      100,   99,  241,   93,   99,  100,  102,  103,  346,  100,
      104,  240,  239,  102,  103,  105,  106,  104,  106,  102,

      103,  102,  105,  104,  103,  346,  238,  106,  105,  107,
      108,  107,  105,  107,  108,  236,  108,  109,  237,  110,
      237,  108,  107,  235,  109,  108,  110,  111,  112,  113,
      109,  114,  110,  111,  111,  112,  113,  113,  114,  115,
      111,  112,  113,  112,  114,  114,  115,  115,  234,  116,
      111,  116,  115,  116,  117,  115,  117,  127,  117,  128,
      203,  129,  116,  246,  127,  246,  128,  117,  129,  130,
      127,  148,  128,  131,  129,  131,  130,  128,  132,  148,
      193,  133,  130,  148,  131,  132,  130,  133,  133,  134,
      321,  132,  321,  337,  133,  337,  134,  134,  149,  135,

      192,  135,  134,  135,  133,  134,  149,  154,  155,  153,
      149,  153,  135,  140,  154,  155,  169,  140,  169,  153,
      154,  155,  172,  153,  172,  156,  191,  169,  190,  156,
      157,  140,  156,  172,  159,  140,  189,  157,  156,  140,
      140,  159,  188,  157,  140,  157,  187,  159,  158,  186,
      185,  140,  152,  150,  140,  158,  140,  141,  140,  160,
      160,  158,  162,  140,  158,  158,  160,  161,  126,  162,
      125,  161,  160,  162,  161,  162,  164,  163,  165,  166,
      161,  163,  123,  164,  163,  165,  166,  167,  122,  164,
      163,  165,  166,  121,  167,  168,  120,  119,   86,   69,

      167,  168,  168,  170,  171,  170,  171,  170,  168,  173,
       68,  173,  171,   61,  173,  171,  170,  174,  175,  174,
      173,   60,   50,  176,  175,  176,  175,   31,  174,  177,
      176,  177,   27,  179,  176,  175,  178,  177,  178,  179,
      177,  179,  180,  178,  181,   26,   25,  178,   14,  180,
      179,  181,  181,  182,  183,  180,  182,  181,   13,   11,
      182,  183,  184,  194,  184,  194,  182,  183,  194,  195,
      196,    7,    0,  184,  194,  224,    0,  196,  195,  197,
      195,  197,  224,  196,  198,  199,    0,  202,  224,  195,
      198,  198,  199,  200,  202,  200,  202,  198,  199,  201,

      199,  201,    0,  201,  200,  202,  204,  228,  204,  197,
      228,    0,  201,  206,  228,  206,  197,  204,  205,  205,
      228,  205,  197,  207,  206,  207,  208,  209,  208,  209,
      205,  209,    0,  208,  207,    0,  210,  208,  210,  211,
      209,  211,  269,  212,  210,  212,  213,  210,  213,  269,
      211,  214,    0,  214,  212,  269,  214,  213,  215,  216,
      215,  216,  214,    0,  217,  215,  217,    0,    0,  215,
      216,  218,    0,  218,  219,  217,  219,    0,  218,  220,
      219,  220,  218,    0,  220,  219,  221,  222,    0,  222,
      220,  221,  225,  221,  222,  223,    0,    0,  222,  225,

      225,  223,  221,  223,  226,  225,  226,  227,  229,  227,
      229,  226,  223,  243,  227,  243,    0,  226,  230,  229,
      227,  231,  230,  231,  230,    0,  247,  232,  247,  232,
        0,  233,  231,  230,  232,    0,    0,  233,  232,  233,
      244,    0,  244,  245,  251,  245,  251,    0,  233,    0,
      245,  244,    0,  243,  245,  243,  248,    0,  248,    0,
        0,    0,  271,  248,  243,  249,  247,  248,  247,  271,
      250,  249,    0,  249,  250,  271,  250,  247,  253,  254,
      253,  254,  249,    0,  251,  250,  251,    0,    0,  253,
      254,  255,  256,  255,  256,  251,    0,  258,  257,  258,

        0,    0,  255,  256,  257,  259,  257,  259,  258,    0,
        0,  261,  260,  261,    0,  257,  259,  260,  261,  260,
        0,  262,  261,  262,  263,  264,  263,  264,  260,    0,
      265,    0,  262,  266,  267,  263,  264,  265,  266,  265,
      266,    0,  267,  268,  267,  268,    0,    0,  265,  266,
      268,  270,    0,  267,  268,  270,    0,  272,  270,  272,
      274,  273,  274,  273,  270,  273,    0,  280,  272,    0,
      281,  274,  281,  280,  273,  280,  282,  283,  282,  283,
      284,  285,    0,  285,  280,  282,  287,  284,  287,  284,
        0,    0,  285,  288,  287,  288,    0,  287,  284,  306,

      288,  306,    0,  289,  288,  289,    0,  290,  306,  290,
      281,  291,  281,  291,  289,    0,    0,  283,  290,  283,
        0,  281,  291,  292,  293,  294,  293,  294,  283,  292,
      295,  292,  295,    0,    0,  293,  294,  296,    0,  296,
      292,  295,  297,  298,  297,  298,    0,  305,  296,  305,
      299,    0,  300,  297,  298,  299,    0,  299,  300,  301,
      300,  301,  308,    0,  308,  322,  299,  310,  312,  300,
      301,  308,  322,  310,  312,  310,  312,  313,  322,  313,
      315,  314,  315,  314,  310,  312,  314,  305,  313,  305,
        0,  315,  314,    0,  316,    0,    0,  323,  305,  309,

      309,  316,  309,  316,  323,  309,    0,  309,    0,  309,
      323,  317,  316,  309,    0,    0,  309,  317,  309,  317,
        0,  318,  318,  324,  318,  324,  326,  318,  317,  318,
      325,    0,  325,  326,  324,  318,  327,  328,  318,  326,
      331,  325,    0,  327,  328,  329,    0,  331,  329,  327,
      328,    0,  329,  331,  332,  333,  334,  338,  329,  339,
        0,  332,  333,  334,  338,    0,  339,  332,  333,  334,
      338,  340,  339,  341,  342,  343,  342,  339,  340,  351,
      341,  351,  343,    0,  340,  342,  341,  344,  343,  348,
      341,    0,  349,  349,  344,  344,  348,    0,    0,  349,

      344,  350,  348,    0,  348,  349,  352,    0,  350,  351,
      353,    0,  352,  352,  350,    0,  351,  353,  356,  352,
      356,  354,  351,  353,  354,  353,    0,    0,  354,  356,
      357,  358,  357,  358,  354,    0,    0,  357,  358,  360,
        0,  357,  358,    0,    0,  360,    0,  360,    0,    0,
        0,    0,    0,    0,    0,    0,  360,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  364,
      364,    0,  364,  364,  364,  364,  364,  364,  364,  364,
      365,    0,  365,    0,    0,  365,    0,  365,  366,    0,

      366,  366,  366,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  368,    0,  368,  369,  369,    0,
      369,  369,  369,  369,  369,  369,  369,  369,  370,  370,
        0,  370,  370,  370,  370,  370,  370,  370,  370,  371,
        0,  371,  371,  371,  372,    0,  372,    0,    0,    0,
        0,  372,    0,  372,  373,    0,  373,  373,    0,  373,
        0,  373,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  375,  375,  375,  375,  375,  375,  375,
        0,  375,  375,  375,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,

      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"


#line 4 "scanner.l"
    #include<stdio.h>
  
    #define KNRM  "\x1B[0m"
    #define KRED  "\x1B[31m"
    #define KGRN  "\x1B[32m"
    #define KYEL  "\x1B[33m"
    #define KBLU  "\x1B[34m"
    #define KMAG  "\x1B[35m"
    #define KCYN  "\x1B[36m"
    #define KWHT  "\x1B[37m"

   #define n_buckets 1000
   int line_num = 1;
   int nested_comment_stack=0;
   char token[100];

   struct table_entry
   {
      void *key, *value;
      struct table_entry *next;
      unsigned int line;
   };

   struct table_entry *s_head[n_buckets];
   struct table_entry *c_head[n_buckets];

   void install_symbol();
   void install_constant();

#line 925 "lex.yy.c"

#define INITIAL 0
#define comment 1
#define string_literal 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 43 "scanner.l"


#line 1115 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 362 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1385 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 45 "scanner.l"
{yylineno++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "scanner.l"

	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 48 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\tPreprocessor Directive\t\t\t%d", KBLU, yytext,yylineno);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "scanner.l"
{printf("%s\n\t\t\tprintf\t\t\t\t\tPre-defined Function\t\t\t\t%d", KBLU, yylineno);strcpy(token, "function");install_symbol();}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "scanner.l"
{printf("%s\n\t\t\tscanf\t\t\t\t\tPre-defined Function\t\t\t\t%d", KBLU, yylineno);strcpy(token, "function");install_symbol();}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "scanner.l"
{BEGIN(comment); nested_comment_stack=1; yymore();}
	YY_BREAK
case YY_STATE_EOF(comment):
#line 52 "scanner.l"
{printf("\nMulti-line Comment: \""); yyless(yyleng-2); ECHO; printf("\", not terminted at line no: %d.", yylineno); yyterminate();}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "scanner.l"
{nested_comment_stack++; yymore();}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "scanner.l"
{yymore();}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 55 "scanner.l"
{yymore();yylineno++;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "scanner.l"
{nested_comment_stack--;
                        if(nested_comment_stack<0)
                        {
                          printf("\nComment: \"%s\", not balanced at line no: %d.", yytext, yylineno);
                          yyterminate();
                        }
                        else if(nested_comment_stack==0)
                        {
                          /*printf("\nMulti-line comment : \"%s\" at line number: %d.", yytext, yylineno);*/
                          BEGIN(INITIAL);
                        }
                        else
                          yymore();
                        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "scanner.l"
{printf("\n Uninitialised comment at line number: %d.", yylineno); yyterminate();}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 73 "scanner.l"
{printf("\nSingle-line comment : \"%s\" at line number: %d.", yytext, yylineno);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "scanner.l"
{ BEGIN(string_literal); yymore();}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "scanner.l"
{yymore(); printf("\nEscape Sequence , line number line number: %d.", yylineno);}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 79 "scanner.l"
{printf("\nUnrecognized escape seqence at line number: %d.", yylineno);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 80 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t String Constant\t\t\t\t%d.",yytext,yylineno);
                                               			 strcpy(token, "String Constant");  install_constant(); BEGIN(INITIAL);}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 82 "scanner.l"
{printf("\nError : Unterminated string: %s at line number: %d.", yytext, yylineno);yylineno++;}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 83 "scanner.l"
{yymore();}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 85 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tInteger Constant\t\t\t%d.", KBLU, yytext,yylineno); strcpy(token, "INT Constant");  install_constant();}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 86 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tFP Constant\t\t\t\t%d.", KBLU, yytext,yylineno); strcpy(token, "FP Constant");  install_constant();}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 87 "scanner.l"
{printf("%s\nError No exponent provided: %s , line number: %d.", KBLU, yytext,yylineno);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 88 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tChar Constant\t\t\t\t%d.", KBLU, yytext,yylineno); strcpy(token, "Char Constant");  install_constant();}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 90 "scanner.l"
{
                                                                                                    if(strstr(yytext, "main")!=NULL)
                                                                                                    {
                                                                                                      printf("%s\n\t\t\tmain\t\t\t\t\tMain Function\t\t\t\t%d", KBLU, yylineno);
                                                                                                      strcpy(token, "function");
                                                                                                      install_symbol();
                                                                                                    }
                                                                                                    else
                                                                                                    {
                                                                                                      printf("%s\n\t\t\t%s\t\t\t\tUser Defined Function\t\t\t%d", KBLU, yytext, yylineno);
                                                                                                      strcpy(token, "User-defined Function");
                                                                                                      install_symbol();
                                                                                                    }
                                                                                                }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 106 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno); strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 107 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 108 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 109 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 110 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 111 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 112 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 113 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 114 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 115 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 116 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 117 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 118 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 119 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 120 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 121 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 122 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 123 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 124 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 125 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 126 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 127 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 128 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 130 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 131 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 132 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 133 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 134 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 135 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 136 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 137 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", KBLU, yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 138 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tIdentifier\t\t\t\t%d.", KBLU, yytext, yylineno); strcpy(token,"Identifier"); install_symbol();}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 143 "scanner.l"
{printf("%s\nArray declaration: %s, Line Number: %d", KBLU, yytext, yylineno);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 144 "scanner.l"
{printf("%s\nPointer declaration: %s, Line Number: %d", KBLU, yytext, yylineno);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 145 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tOperator\t\t\t\t%d.", KBLU, yytext,yylineno); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 146 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tSeparator\t\t\t\t%d", KBLU, yytext, yylineno);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 147 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tDelimiter\t\t\t\t%d", KBLU, yytext, yylineno);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 148 "scanner.l"
{printf("%s\n\t\t\t%s\t\t\t\t\tInvalid Character\t\t\t%d.", KRED, yytext, yylineno);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 149 "scanner.l"
ECHO;
	YY_BREAK
#line 1558 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string_literal):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 362 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 362 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 361);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 149 "scanner.l"



unsigned int get_hash(char *str)
{
    unsigned int hash = 5381;
    int c;

    while ((c = *str++))
        hash = ((hash << 5) + hash) + c; /* hash * 33 + c */

    return hash%1000;
}

struct table_entry *create_node()
{
  struct table_entry *temp = (struct table_entry *)malloc(sizeof(struct table_entry));
  if(temp==NULL)
  {
    printf("\nCould not allocate memory for the symbol table.");
    exit(1);
  }
  temp->next = NULL;
  return temp;
}

void insert(struct table_entry *head[], unsigned int index, void *key, void *value, unsigned int line)
{
  struct table_entry *temp = create_node();
  temp->key = key;
  temp->value = value;
  temp->line = line;
  temp->next = head[index];

  head[index] = temp;
}

struct table_entry *search(struct table_entry *head, void *key)
{
  struct table_entry *temp = head;
  while(temp!=NULL)
  {
    if(strcmp((char *)temp->key, (char *)key)==0)
      return temp;
    temp = temp->next;
  }
  return temp;
}



void install_symbol()
{
  char *key = (char *)malloc(sizeof(char)*yyleng);
  char *value = (char *)malloc(sizeof(char)*yyleng);

  strcpy(key, yytext);
  strcpy(value, token);
  unsigned int index = get_hash(key);


  struct table_entry *temp = search(s_head[index], key);
  if(temp==NULL)
    insert(s_head, index, key, value, yylineno);
}

void install_constant()
{
  char *key = (char *)malloc(sizeof(char)*yyleng);
  char *value = (char *)malloc(sizeof(char)*yyleng);

  strcpy(key, yytext);
  strcpy(value, token);
  unsigned int index = get_hash(key);

  struct table_entry *temp = search(c_head[index], key);
  if(temp==NULL);
    insert(c_head, index, key, value, yylineno);
}


void print_symbol_table()
{
  int i;
  printf("%s\n=========================================================================================================================================", KMAG);
  printf("%s\n\t\t\t\t\t\t\t\tSYMBOL TABLE", KMAG);
  printf("%s\n=========================================================================================================================================", KMAG);  
  printf("%s\n\t\t\t\tToken\t\t\t\tToken Type\t\t\t\tLine Number\n", KCYN);
  for(int i=0;i<n_buckets;i++)
  {
      if(s_head[i]!=NULL)
      {
        struct table_entry *temp = s_head[i];
        while(temp!=NULL)
        {
          printf("%s\n\t\t\t\t%s\t\t\t\t<%s>\t\t\t\t%d", KWHT, (char *)temp->key, (char *)temp->value, temp->line);
          temp = temp->next;
        }
      }
  }
  printf("\n");
}

void print_constant_table()
{
  int i;
  printf("%s\n=========================================================================================================================================", KMAG);
  printf("%s\n\t\t\t\t\t\t\tCONSTANT TABLE", KMAG);
  printf("%s\n=========================================================================================================================================", KMAG);  
  printf("%s\n\t\t\t\tToken\t\t\t\tToken Type\t\t\t\tLine Number\n", KCYN);
  for(int i=0;i<n_buckets;i++)
  {
      if(c_head[i]!=NULL)
      {
        struct table_entry *temp = c_head[i];
        while(temp!=NULL)
        {
          printf("%s\n\t\t\t\t%s\t\t\t\t<%s>\t\t\t\t%d", KWHT, (char *)temp->key, (char *)temp->value, temp->line);
          temp = temp->next;
        }
      }
  }
  printf("\n");
}


int main()
{
  FILE *fp;
  fp = fopen("sample.c", "r");
  yyin = fp;
  printf("\n===========================================================================================================================================================");
  printf("\n\t\t\tTOKEN\t\t\t\tTOKEN TYPE\t\t\t\tLINE NUMBER");
  printf("\n===========================================================================================================================================================");
  int newtoken = 1;
  while(newtoken){
	newtoken = yylex();
  }
  print_symbol_table();
  print_constant_table();
  return 0;
}
int yywrap()
{
  return 1;
}

