
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (yy_size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[352] =
    {   0,
        2,    2,    0,    0,    0,    0,   61,   59,    2,    1,
       56,   11,   59,   56,   56,   59,   56,   56,   56,   57,
       56,   17,   56,   17,   58,   56,   59,   56,   53,   17,
       59,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   59,    2,   53,   53,
       53,   53,   53,   53,   53,   53,    6,    7,    6,    6,
       16,   15,   14,   60,    2,   56,    0,    0,    0,    0,
        9,   55,   17,   17,    4,   10,   17,   17,   53,   53,
        0,    0,   18,   17,   17,   17,   18,   18,   18,   53,
       53,   53,   53,   53,   53,   28,   53,   53,   53,   53,

       53,   53,   36,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,    2,    0,    0,    0,    0,    0,
        0,    0,    0,   53,   28,   53,   53,   53,   53,   53,
       53,   53,    8,    5,   13,   12,   13,    0,   19,   55,
       17,   10,    0,   54,    0,    0,   17,   17,   17,   17,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   34,   53,   37,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   53,   53,
       53,   37,   53,   53,   53,   53,   53,    0,   21,   53,

       23,   24,   53,   53,   53,   53,   30,   31,   53,   53,
       35,   38,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   50,   53,   53,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   24,   53,   53,    0,   38,
       53,   53,   53,   50,    0,   22,   25,   53,   53,   53,
       53,   33,   53,   53,   41,   53,   53,   53,   53,   53,
       53,   48,   53,   53,   52,    0,    0,    0,    0,    0,
       53,   33,    0,   41,   53,   53,    0,   53,   53,   29,
       32,   53,   40,   42,   43,   44,   45,   46,   53,   53,
       53,    0,    0,    0,   29,    0,    0,    0,   42,   53,

        0,   53,   27,   53,   47,   53,   53,    0,    0,    0,
       20,   53,   53,   53,   53,   53,   53,   53,   53,    0,
       26,   39,   49,   51,    0,    0,   20,   53,   53,   53,
       53,   53,   53,   53,   49,    0,    0,   53,   53,   53,
       53,   53,   53,   53,    0,   53,   53,   53,    3,   53,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   25,   41,   42,   43,   44,
       45,   46,   25,   47,   48,   49,   50,   51,   52,   53,
       54,   55,    1,   56,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[57] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        5,    1,    6,    1,    1,    1,    1,    6,    7,    1,
        1,    6,    8,    1,    9,    9,   10,    1,    1,    1,
       11,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    1
    } ;

static yyconst flex_int16_t yy_base[366] =
    {   0,
        0,   55,   55,   57,   58,   59,  637, 1341,   65, 1341,
      612, 1341,  593,  607,   54,    0, 1341,   78,   52, 1341,
       55,   53,   80,   82, 1341,  598,  573,  569,   85,  116,
      564,  154,  155,  156,   49,  152,  161,  175,  171,  177,
      187,  189,  186,  136,  198,  203,   58,  247,  541,  214,
      213,  219,  215,   44,  220,  235, 1341, 1341,  550,  553,
     1341, 1341, 1341,  293,  105, 1341,  511,  541,  253,  272,
     1341,    0,  173,  290, 1341,    0,  191,  251,  247,  269,
      259,  291, 1341,   94,  531,  296,  293,  264,  312,  314,
      328,  329,  322,  258,  328,  329,  309,  334,  341,  354,

      356,  357,  359,  368,  366,  367,  382,  386,  383,  394,
      397,  405,  407,  412,    0,  509,  502,  502,  496,  489,
      137,  482,  479,  416,  425,  427,  435,  429,  444,  447,
      455,  457, 1341, 1341, 1341, 1341,  505,  464, 1341,    0,
      315,    0,  300, 1341,  450,  477,  474,  319,  472,  490,
      473,  474,  491,  496,  514,  500,  525,  533,  528,  543,
      542,  544,  545,  553,  561,  562,  564,  565,  472,  569,
      574,  575,  582,  594,  576,  600,  609,  610,  478,  446,
      418,  418,  413,  414,  401,  397,  384,  383,  609,  617,
      626,  662,  635,  636,  634,  642,  655,  370,  635,  661,

      647,  662,  667,  677,  681,  680,  684,  685,  697,  698,
      701,  704,  711,  714,  721,  724,  653,  739,  741,  749,
      737,  743,  751,  748,  756,  755,  350,  359,  348,  348,
      336,  322,  291,  288,  281,  808,  769,  772,  364,  813,
      782,  792,  785,  816,  255,  788,  795,  798,  812,  826,
      829,  830,  836,  833,  846,  849,  850,  862,  856,  814,
      875,  878,  874,  882,  877,  254,  242,  220,  229,  201,
      889,  930,  934,  935,  905,  899,  201,  904,  911,  917,
      923,  927,  931,  943,  947,  948,  951,  955,  961,  971,
      967,  197,  177,  167, 1008, 1014,  186, 1015, 1028,  985,

      154,  986,  989,  990, 1002, 1005, 1031, 1043,  143,  107,
      436, 1009, 1021, 1044, 1045, 1060, 1061, 1063, 1072,  223,
     1064, 1080, 1081, 1082,   76,   75,  486, 1083, 1084, 1092,
     1100, 1091, 1108, 1111,    0,  354,    0, 1116, 1125, 1120,
     1134, 1130, 1135, 1146,   55, 1142, 1145, 1148, 1341, 1160,
     1341, 1213, 1224, 1235, 1243, 1248, 1259, 1264, 1273, 1284,
     1289, 1299, 1309, 1318, 1329
    } ;

static yyconst flex_int16_t yy_def[366] =
    {   0,
      351,    1,  352,  352,  353,  353,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  354,  351,  355,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  356,  351,
      351,  356,  356,  356,   34,   34,   34,   34,   36,   34,
       34,   34,   34,   36,   34,   34,  351,  351,   34,   34,
       34,   36,   34,   42,   36,   34,  351,  351,  351,  351,
      351,  351,  351,  357,  351,  351,  351,  351,  355,  355,
      351,  358,  351,  359,  351,  360,  351,  351,   34,   34,
      351,  361,  351,  351,  351,  356,  356,  351,  361,  356,
      356,  356,   34,   36,   36,   36,   36,   36,   36,   34,

       34,   34,   34,   34,   36,   36,   34,   34,   34,   34,
       34,   34,   36,   36,   48,  351,  351,  351,  351,  351,
      351,  351,  351,   34,   34,   34,   34,   36,   34,   34,
       34,   36,  351,  351,  351,  351,  357,  351,  351,  358,
      351,  360,  351,  351,  361,  361,  351,  351,  351,  356,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   36,   36,
       36,   36,   36,   36,   34,   34,   34,   34,   36,  351,
      351,  351,  351,  351,  351,  351,  351,  351,   36,   36,
       34,   34,   34,   34,   36,   36,   36,  351,   36,   36,

       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   34,   34,   34,   34,
       34,   36,   36,   36,   36,   36,  351,  351,  351,  351,
      351,  351,  351,  351,  351,   36,   36,   36,  362,   36,
       36,   36,   36,   36,  351,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   34,
       34,   34,   36,   36,   36,  351,  351,  351,  351,  351,
       36,   36,  363,   36,   36,   36,  351,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,  351,  351,  351,   36,  351,  364,  363,   36,   36,

      351,   36,   36,   36,   36,   36,   36,  351,  351,  364,
      351,   34,   34,   36,   36,   34,   34,   34,   34,  351,
       34,   34,   34,   34,  351,  351,  351,   34,   34,   34,
       34,   36,   34,   34,  299,  351,  365,   34,   34,   34,
       34,   34,   34,   34,  365,   36,   36,   36,  351,   36,
        0,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351
    } ;

static yyconst flex_int16_t yy_nxt[1398] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,    8,   29,   30,   17,    8,   17,   31,
       29,   32,   33,   34,   35,   36,   37,   38,   29,   39,
       29,   40,   29,   29,   29,   29,   41,   42,   43,   44,
       45,   46,   29,   29,   29,   47,   48,   58,   48,   58,
       62,   62,   66,   63,   63,   66,   65,   59,   65,   59,
       66,   73,   60,   66,   60,   66,   66,  349,   74,   66,
       80,   69,  129,  130,   95,   64,   64,   80,   49,   50,
       70,   51,   75,   96,   52,   71,   53,   76,   77,   66,

       78,   66,   54,   79,   55,   56,   65,   74,   65,  308,
      147,   81,  148,   66,  185,   82,   83,   83,  311,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   84,
       83,   84,   85,   83,   86,   83,   83,   83,   83,   83,
       87,   87,   88,   83,   83,   83,   89,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   84,   79,   79,   79,  185,  186,   80,  326,  112,
       81,   81,   81,   80,   82,   82,   82,   92,   80,  320,
       80,   73,   80,   97,   93,   98,   80,  311,   74,   80,

       94,   91,  100,   90,   99,  101,   80,  103,   80,   73,
      309,  308,   80,   80,  104,   80,   74,   80,   80,  102,
       80,  105,  106,   80,   80,   80,  336,  107,  108,   80,
       80,   80,  230,   80,   80,  301,   80,  109,  294,  111,
      110,  114,  113,  337,   80,   80,   80,   80,  115,   95,
      115,   80,   80,   80,  126,  103,   69,  101,  125,  128,
       80,   80,  127,  131,  293,  351,   80,   77,  230,   78,
      351,   80,   80,   80,  351,   69,   74,  143,   80,  132,
      116,  117,  143,  118,   70,   80,  119,  144,  120,  351,
      230,   80,  144,  351,  121,  292,  122,  123,  136,   80,

       80,  155,  136,   84,  277,   84,   85,   80,  141,  145,
       80,   79,  147,   80,  150,  230,  136,   81,  143,   81,
      137,   82,   81,   82,  136,  136,   82,  270,  144,  136,
      145,  147,   79,  148,  269,  147,  136,  148,   81,  136,
       81,  136,   82,  136,   82,   84,   79,   79,  136,  239,
       80,  239,   80,  154,   81,   81,  158,  336,   82,   82,
       80,   80,  151,  152,  156,  239,   80,  239,  268,   80,
       80,   80,   80,  230,  337,   80,  153,   80,  157,  267,
       80,   80,   80,  159,   80,   80,   80,   80,   80,  160,
       80,  266,   80,   80,   80,   80,  230,   80,  161,   80,

       80,   80,  162,   80,  166,  163,   80,   80,   80,  165,
       80,  245,   80,   80,  171,  167,  164,   80,   80,   80,
       80,   80,  235,  169,   80,   80,  168,   80,   80,  172,
       80,  234,   80,  173,  233,   80,   80,  327,   80,  327,
      170,   80,  174,   80,  175,  232,  177,  189,  178,   80,
       80,  179,  176,   80,   80,   80,   80,  231,   80,   80,
       80,  230,  229,   80,   80,   80,   80,  228,  145,   80,
       80,  191,  193,   80,  190,   80,   81,  227,   80,   80,
       82,   80,   80,  192,  195,   80,   80,  327,  194,  327,
      149,   80,  149,   80,  175,  145,  197,  198,  178,   80,

       80,  170,  196,   81,   80,  200,  147,   82,  150,   80,
      136,   80,   80,   80,  136,  216,   81,  199,   80,  226,
       82,   80,   80,  188,   80,  187,  201,   80,  136,   80,
       80,  205,  137,  184,   80,   80,  136,  136,   80,  183,
       80,  136,  202,  182,   80,   80,  181,  180,  136,  149,
      139,  136,   80,  136,  138,  136,   80,  206,   80,   80,
      136,  203,  204,   80,   80,  134,   80,  133,  207,   80,
      208,   80,   80,  210,   80,   80,   80,   80,  209,  124,
       80,   80,   80,   80,   80,   66,   80,   80,   80,  211,
       66,   80,   80,   80,   66,   80,   80,   80,  212,   80,

       80,  213,   80,   80,  217,   80,   80,   80,   80,   80,
       80,  215,   80,  214,   80,   80,   80,   80,   80,   66,
      222,   80,  218,   80,  219,   80,   80,   80,   66,  221,
      220,   80,   67,   66,   80,   80,  351,   80,   80,  223,
       80,  225,  351,  224,   80,  351,   80,   80,   80,  237,
       80,  351,   80,   80,   80,  236,  351,  238,   80,  351,
       80,   80,  351,  239,   80,  239,   80,   80,  351,   80,
       80,  351,  240,   80,   80,   80,   80,  242,   80,   80,
       80,  243,  241,   80,   80,   80,   80,   80,   80,  244,
       80,   80,  351,   80,   80,  351,   80,  257,   80,   80,

       80,  246,   80,   80,   80,   80,   80,   80,   80,  351,
       80,  351,  351,   80,   80,  247,  248,  351,   80,   80,
       80,  250,   80,   80,   80,   80,   80,   80,   80,   80,
      249,  351,   80,   80,  351,  351,   80,   80,   80,   80,
       80,   80,   80,  251,   80,   80,  252,   80,  351,   80,
       80,  351,   80,   80,   80,   80,   80,   80,  253,  256,
      254,  351,   80,   80,   80,   80,   80,   80,   80,  255,
       80,  261,   80,   80,  259,   80,   80,   80,  258,   80,
       80,   80,  260,   80,   80,   80,  262,   80,  263,   80,
      265,   80,   80,   80,   80,   80,   80,   80,   80,   80,

       80,  351,  351,   80,  264,  351,  351,   80,   80,  239,
      271,  239,   80,   80,  239,   80,  239,  239,  351,  239,
      272,   80,  276,   80,   80,   80,   80,  275,   80,   80,
      274,   80,  351,   80,   80,   80,   80,   80,   80,   80,
       80,  278,  351,  351,   80,   80,  351,   80,  351,   80,
       80,   80,  288,  279,   80,   80,   80,   80,   80,   80,
       80,  280,  351,  351,   80,   80,  351,   80,   80,   80,
       80,   80,  281,   80,   80,  351,  283,   80,   80,   80,
      351,   80,   80,  284,  282,   80,  285,   80,   80,   80,
       80,   80,   80,   80,  351,  286,  351,   80,   80,   80,

      351,   80,   80,   80,  287,   80,   80,  351,   80,   80,
      289,  351,  351,   80,   80,   80,   80,  290,   80,   80,
       80,  291,   80,   80,  295,   80,   80,  351,  351,   80,
       80,  239,   80,  239,   80,  296,  239,  296,  239,  299,
       80,   80,  300,  351,  297,   80,   80,   80,   80,  351,
      351,   80,   80,  302,   80,  351,   80,   80,   80,  303,
       80,  351,  304,   80,   80,  351,   80,  351,   80,   80,
       80,   80,   80,   80,   80,   80,   80,  351,   80,   80,
      351,  351,   80,   80,   80,  351,   80,   80,   80,   80,
       80,   80,   80,  351,   80,   80,   80,  305,   80,   80,

       80,  351,   80,   80,   80,  351,  306,   80,  307,  239,
       80,  239,   80,   80,   80,  296,  296,  296,  296,   80,
      319,  321,  351,   80,  297,  297,   80,   80,   80,   80,
       80,   80,   80,   80,  351,  351,  322,   80,   80,  323,
       80,   80,   80,   80,  351,   80,   80,  328,   80,   80,
      351,   80,   80,   80,   80,  351,  351,   80,  351,   80,
       80,  312,  313,  351,  314,  329,  324,  315,  351,  316,
      351,   80,   80,  351,   80,  317,  116,  117,  318,  118,
       80,  351,  119,   80,  120,  330,   80,   80,  331,  351,
      325,   80,   80,  123,   80,   80,   80,   80,   80,  333,

      351,   80,   80,   80,  332,   80,  335,  334,   80,  351,
       80,   80,   80,   80,  338,   80,   80,  351,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,  351,
       80,   80,   80,  339,  342,  239,  340,  239,   80,   80,
      351,  351,   80,   80,   80,  351,   80,   80,  341,   80,
      344,  347,  343,  351,   80,   80,   80,  346,   80,  351,
       80,   80,  341,   80,   80,   80,   80,  341,   80,   80,
      351,  351,   80,   80,   80,  351,  351,   80,   80,   80,
      341,  348,  351,  350,   80,   80,   80,  351,   80,   80,
       80,   80,  351,  341,   80,  341,  341,   80,  351,  351,

       80,   80,  351,   80,  351,  351,  351,  351,  351,  351,
      351,  351,   80,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   68,   68,  351,   68,   68,
       68,   68,   68,   68,   68,   68,   72,  351,   72,  351,
      351,   72,  351,   72,   80,  351,   80,   80,   80,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      140,  351,  140,   83,   83,  351,   83,   83,   83,   83,
       83,   83,   83,   83,  142,  142,  351,  142,  142,  142,
      142,  142,  142,  142,  142,  146,  351,  146,  146,  146,

      273,  351,  273,  351,  351,  351,  351,  273,  351,  273,
      298,  351,  298,  298,  351,  298,  351,  298,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  345,
      345,  345,  345,  345,  345,  345,  351,  345,  345,  345,
        7,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351

    } ;

static yyconst flex_int16_t yy_chk[1398] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    3,    2,    4,
        5,    6,   15,    5,    6,   19,    9,    3,    9,    4,
       21,   22,    3,   19,    4,   15,   21,  345,   22,   47,
       35,   18,   54,   54,   35,    5,    6,   35,    2,    2,
       18,    2,   23,   35,    2,   18,    2,   23,   24,   18,

       24,   23,    2,   29,    2,    2,   65,   24,   65,  326,
       84,   29,   84,   47,  325,   29,   30,   30,  310,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   32,   33,   34,  121,  121,   44,  309,   44,
       32,   33,   34,   36,   32,   33,   34,   34,   44,  301,
       36,   73,   37,   36,   34,   36,   36,  297,   73,   37,

       34,   33,   37,   32,   36,   37,   38,   39,   40,   77,
      294,  293,   39,   38,   39,   40,   77,   43,   41,   38,
       42,   40,   41,   39,   43,   41,  320,   42,   42,   45,
       43,   41,  292,   42,   46,  277,   45,   42,  270,   43,
       42,   46,   45,  320,   51,   50,   53,   46,   48,   50,
       48,   51,   50,   53,   51,   52,   69,   51,   50,   53,
       52,   55,   52,   55,  269,   69,   56,   78,  268,   78,
       69,   52,   55,   56,   69,   70,   78,   81,   79,   56,
       48,   48,   88,   48,   70,   79,   48,   81,   48,   70,
      267,   79,   88,   70,   48,  266,   48,   48,   64,   94,

       80,   94,   64,   74,  245,   74,   74,   80,   74,   82,
       94,   87,   86,   80,   86,  235,   64,   82,  143,   87,
       64,   82,   86,   87,   64,   64,   86,  234,  143,   64,
       89,  141,   90,  141,  233,  148,   64,  148,   89,   64,
       90,   64,   89,   64,   90,   74,   91,   92,   64,  230,
       97,  230,   97,   93,   91,   92,   97,  336,   91,   92,
       93,   97,   90,   91,   95,  239,   93,  239,  232,   95,
       96,   95,   96,  231,  336,   98,   92,   98,   96,  229,
       95,   96,   99,   98,   99,  100,   98,  101,  102,   99,
      103,  228,  100,   99,  101,  102,  227,  103,  100,  104,

      101,  102,  101,  103,  106,  102,  104,  105,  106,  105,
      106,  198,  104,  107,  109,  106,  104,  108,  105,  106,
      107,  109,  188,  108,  108,  110,  107,  109,  111,  109,
      108,  187,  110,  110,  186,  111,  112,  311,  110,  311,
      108,  111,  111,  112,  112,  185,  113,  124,  113,  112,
      113,  114,  112,  114,  124,  114,  125,  184,  126,  113,
      124,  183,  182,  125,  114,  126,  127,  181,  145,  125,
      128,  126,  128,  127,  125,  129,  145,  180,  130,  127,
      145,  128,  129,  127,  130,  130,  131,  327,  129,  327,
      149,  130,  147,  131,  131,  146,  132,  138,  132,  131,

      132,  130,  131,  146,  151,  152,  150,  146,  150,  132,
      137,  151,  152,  169,  137,  169,  150,  151,  152,  179,
      150,  179,  153,  123,  169,  122,  153,  154,  137,  153,
      179,  156,  137,  120,  154,  153,  137,  137,  156,  119,
      154,  137,  154,  118,  156,  155,  117,  116,  137,   85,
       68,  137,  155,  137,   67,  137,  157,  157,  155,  159,
      137,  155,  155,  157,  158,   60,  159,   59,  158,  157,
      159,  158,  159,  161,  160,  162,  163,  158,  160,   49,
      161,  160,  162,  163,  164,   31,  161,  160,  162,  163,
       28,  164,  165,  166,   27,  167,  168,  164,  165,  165,

      166,  166,  167,  168,  170,  165,  166,  175,  167,  168,
      170,  168,  170,  167,  175,  171,  172,  171,  172,   26,
      175,  170,  171,  173,  172,  173,  171,  172,   14,  174,
      173,  176,   13,   11,  173,  174,    7,  174,  176,  176,
      177,  178,    0,  177,  176,    0,  174,  177,  178,  190,
      189,    0,  189,  177,  178,  189,    0,  191,  190,    0,
      190,  189,    0,  192,  191,  192,  193,  194,    0,  190,
      191,    0,  193,  193,  194,  195,  199,  195,  199,  193,
      194,  196,  194,  196,  217,  196,  195,  199,  201,  197,
      201,  217,    0,  192,  196,    0,  197,  217,  197,  201,

      192,  200,  200,  202,  200,  202,  192,  197,  203,    0,
      203,    0,    0,  200,  202,  203,  204,    0,  204,  203,
      204,  206,  205,  206,  205,  207,  208,  207,  208,  204,
      205,    0,  206,  205,    0,    0,  207,  208,  209,  210,
      209,  210,  211,  209,  211,  212,  210,  212,    0,  209,
      210,    0,  213,  211,  213,  214,  212,  214,  213,  216,
      214,    0,  215,  213,  215,  216,  214,  216,  221,  215,
      218,  221,  219,  215,  219,  221,  216,  218,  218,  219,
      220,  221,  220,  218,  222,  219,  222,  220,  223,  224,
      226,  224,  223,  220,  223,  222,  226,  225,  226,  225,

      224,    0,    0,  223,  225,    0,    0,  226,  225,  236,
      237,  236,  237,  238,  240,  238,  240,  244,    0,  244,
      238,  237,  243,  241,  238,  241,  243,  242,  243,  246,
      241,  246,    0,  242,  241,  242,  247,  243,  247,  248,
      246,  248,    0,    0,  242,  260,    0,  247,    0,  236,
      248,  236,  260,  249,  240,  249,  240,  244,  260,  244,
      236,  250,    0,    0,  249,  240,    0,  250,  244,  250,
      251,  252,  251,  252,  254,    0,  254,  253,  250,  253,
        0,  251,  252,  256,  253,  254,  257,  255,  253,  255,
      256,  257,  256,  257,    0,  258,    0,  259,  255,  259,

        0,  256,  257,  258,  259,  258,  261,    0,  259,  262,
      261,    0,    0,  261,  258,  263,  262,  263,  265,  261,
      265,  264,  262,  264,  271,  264,  263,    0,    0,  265,
      271,  272,  271,  272,  264,  273,  274,  273,  274,  275,
      276,  271,  276,    0,  273,  278,  275,  278,  275,    0,
        0,  276,  279,  278,  279,    0,  278,  275,  280,  279,
      280,    0,  282,  279,  281,    0,  281,    0,  282,  280,
      282,  272,  283,  272,  283,  281,  274,    0,  274,  282,
        0,    0,  272,  283,  284,    0,  284,  274,  285,  286,
      285,  286,  287,    0,  287,  284,  288,  289,  288,  285,

      286,    0,  289,  287,  289,    0,  290,  288,  291,  295,
      291,  295,  290,  289,  290,  296,  298,  296,  298,  291,
      300,  302,    0,  290,  296,  298,  300,  302,  300,  302,
      303,  304,  303,  304,    0,    0,  304,  300,  302,  306,
      312,  303,  304,  305,    0,  305,  306,  312,  306,  295,
        0,  295,  313,  312,  305,    0,    0,  306,    0,  313,
      295,  299,  299,    0,  299,  313,  307,  299,    0,  299,
        0,  299,  307,    0,  307,  299,  308,  308,  299,  308,
      299,    0,  308,  307,  308,  314,  315,  314,  315,    0,
      308,  316,  317,  308,  318,  321,  314,  315,  316,  317,

        0,  318,  321,  319,  316,  317,  319,  318,  321,    0,
      319,  322,  323,  324,  328,  329,  319,    0,  322,  323,
      324,  328,  329,  330,  322,  323,  324,  328,  329,    0,
      330,  331,  332,  329,  332,  341,  330,  341,  331,  333,
        0,    0,  334,  332,  331,    0,  333,  338,  331,  334,
      334,  340,  333,    0,  338,  334,  339,  339,  340,    0,
      338,  342,  338,  339,  340,  341,  343,  342,  342,  339,
        0,    0,  341,  343,  342,    0,    0,  344,  341,  343,
      344,  343,    0,  346,  344,  346,  347,    0,  347,  348,
      344,  348,    0,  347,  346,  350,  348,  347,    0,    0,

      348,  350,    0,  350,    0,    0,    0,    0,    0,    0,
        0,    0,  350,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  354,  354,    0,  354,  354,
      354,  354,  354,  354,  354,  354,  355,    0,  355,    0,
        0,  355,    0,  355,  356,    0,  356,  356,  356,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      358,    0,  358,  359,  359,    0,  359,  359,  359,  359,
      359,  359,  359,  359,  360,  360,    0,  360,  360,  360,
      360,  360,  360,  360,  360,  361,    0,  361,  361,  361,

      362,    0,  362,    0,    0,    0,    0,  362,    0,  362,
      363,    0,  363,  363,    0,  363,    0,  363,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  365,
      365,  365,  365,  365,  365,  365,    0,  365,  365,  365,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"


#line 4 "scanner.l"
   #define n_buckets 1000
   int line_num = 1;
   int nested_comment_stack=0;
   char token[100];

   struct table_entry
   {
      void *key, *value;
      struct table_entry *next;
      unsigned int line;
   };

   struct table_entry *s_head[n_buckets];
   struct table_entry *c_head[n_buckets];

   void install_symbol();
   void install_constant();


#line 902 "lex.yy.c"

#define INITIAL 0
#define comment 1
#define string_literal 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 33 "scanner.l"


#line 1092 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 352 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1341 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 35 "scanner.l"
{yylineno++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "scanner.l"

	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 38 "scanner.l"
{printf("\n\t\t\t%s\t\t\tPreprocessor Directive\t\t\t%d",yytext,yylineno);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "scanner.l"
{BEGIN(comment); nested_comment_stack=1; yymore();}
	YY_BREAK
case YY_STATE_EOF(comment):
#line 41 "scanner.l"
{printf("\nMulti-line Comment: \""); yyless(yyleng-2); ECHO; printf("\", not terminted at line no: %d.", yylineno); yyterminate();}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "scanner.l"
{nested_comment_stack++; yymore();}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "scanner.l"
{yymore();}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 44 "scanner.l"
{yymore();yylineno++;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 45 "scanner.l"
{nested_comment_stack--;
                        if(nested_comment_stack<0)
                        {
                          printf("\nComment: \"%s\", not balanced at line no: %d.", yytext, yylineno);
                          yyterminate();
                        }
                        else if(nested_comment_stack==0)
                        {
                          /*printf("\nMulti-line comment : \"%s\" at line number: %d.", yytext, yylineno);*/
                          BEGIN(INITIAL);
                        }
                        else
                          yymore();
                        };
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "scanner.l"
{printf("\n Uninitialised comment at line number: %d.", yylineno); yyterminate();}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "scanner.l"
{printf("\nSingle-line comment : \"%s\" at line number: %d.", yytext, yylineno);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 66 "scanner.l"
{ BEGIN(string_literal); yymore();}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 67 "scanner.l"
{yymore(); printf("\nEscape Sequence , line number line number: %d.", yylineno);}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 68 "scanner.l"
{printf("\nUnrecognized escape seqence at line number: %d.", yylineno);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 69 "scanner.l"
{printf("\nString: %s at line number: %d.", yytext, yylineno);
                                    strcpy(token, "String Literal");  install_constant(); BEGIN(INITIAL);}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 71 "scanner.l"
{printf("\nUnterminated string: %s at line number: %d.", yytext, yylineno);yylineno++;}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 72 "scanner.l"
{yymore();}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 75 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tFP Constant\t\t\t\t%d.",yytext,yylineno);
                                                                      strcpy(token, "FP Constant");  install_constant();}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 77 "scanner.l"
{printf("\nError No exponent provided: %s , line number: %d.",yytext,yylineno);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 "scanner.l"
{printf("\nConstant: %s , line number: %d.",yytext,yylineno);}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 80 "scanner.l"
{
                                                                                                    if(strstr(yytext, "main")!=NULL)
                                                                                                    {
                                                                                                      printf("\n\t\t\tmain\t\t\t\t\tMain Function\t\t\t\t%d", yylineno);
                                                                                                      strcpy(token, "Main");
                                                                                                      install_symbol();
                                                                                                    }
                                                                                                    else
                                                                                                    {
                                                                                                      printf("\n\t\t\t%s\t\t\t\tUser Defined Function\t\t\t%d", yytext, yylineno);
                                                                                                      strcpy(token, "User-defined Function");
                                                                                                      install_symbol();
                                                                                                    }
                                                                                                }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 96 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno); strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 97 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 102 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 103 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 104 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 105 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 106 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 107 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 108 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 109 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 110 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 111 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 112 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 113 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 114 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 115 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 116 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 117 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 118 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 119 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 120 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 121 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 122 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 123 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 124 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 125 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 126 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 127 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tKeyword\t\t\t\t\t%d.", yytext, yylineno);  strcpy(token,"Keyword");  install_symbol();}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 128 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tIdentifier\t\t\t\t%d.", yytext, yylineno); strcpy(token,"Identifier"); install_symbol();}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 133 "scanner.l"
{printf("\nArray declaration: %s, Line Number: %d", yytext, yylineno);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 134 "scanner.l"
{printf("\nPointer declaration: %s, Line Number: %d", yytext, yylineno);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 135 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tOperator\t\t\t\t%d.",yytext,yylineno); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 136 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tSeparator\t\t\t\t%d", yytext, yylineno);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 137 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tDelimiter\t\t\t\t%d", yytext, yylineno);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 138 "scanner.l"
{printf("\n\t\t\t%s\t\t\t\t\tInvalid Character\t\t\t%d.", yytext, yylineno);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 139 "scanner.l"
ECHO;
	YY_BREAK
#line 1521 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string_literal):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 352 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 352 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 351);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 139 "scanner.l"



unsigned int get_hash(char *str)
{
    unsigned int hash = 5381;
    int c;

    while ((c = *str++))
        hash = ((hash << 5) + hash) + c; /* hash * 33 + c */

    return hash%1000;
}

struct table_entry *create_node()
{
  struct table_entry *temp = (struct table_entry *)malloc(sizeof(struct table_entry));
  if(temp==NULL)
  {
    printf("\nCould not allocate memory for the symbol table.");
    exit(1);
  }
  temp->next = NULL;
  return temp;
}

void insert(struct table_entry *head[], unsigned int index, void *key, void *value, unsigned int line)
{
  struct table_entry *temp = create_node();
  temp->key = key;
  temp->value = value;
  temp->line = line;
  temp->next = head[index];

  head[index] = temp;
}

struct table_entry *search(struct table_entry *head, void *key)
{
  struct table_entry *temp = head;
  while(temp!=NULL)
  {
    if(strcmp((char *)temp->key, (char *)key)==0)
      return temp;
    temp = temp->next;
  }
  return temp;
}



void install_symbol()
{
  char *key = (char *)malloc(sizeof(char)*yyleng);
  char *value = (char *)malloc(sizeof(char)*yyleng);

  strcpy(key, yytext);
  strcpy(value, token);
  unsigned int index = get_hash(key);


  struct table_entry *temp = search(s_head[index], key);
  if(temp==NULL)
    insert(s_head, index, key, value, yylineno);
}

void install_constant()
{
  char *key = (char *)malloc(sizeof(char)*yyleng);
  char *value = (char *)malloc(sizeof(char)*yyleng);

  strcpy(key, yytext);
  strcpy(value, token);
  unsigned int index = get_hash(key);

  struct table_entry *temp = search(c_head[index], key);
  if(temp==NULL);
    insert(c_head, index, key, value, yylineno);
}


void print_symbol_table()
{
  int i;
  printf("\n\n\n\t\t\t\t\t\tSYMBOL TABLE\n\t\t\t\t\t\t=============\n");
  printf("\n\t\t\t\tToken\t\t\t\tToken Type\t\t\t\tLine Number\n");
  for(int i=0;i<n_buckets;i++)
  {
      if(s_head[i]!=NULL)
      {
        struct table_entry *temp = s_head[i];
        while(temp!=NULL)
        {
          printf("\n\t\t\t\t%s\t\t\t\t<%s>\t\t\t\t%d", (char *)temp->key, (char *)temp->value, temp->line);
          temp = temp->next;
        }
      }
  }
  printf("\n");
}

void print_constant_table()
{
  int i;
  printf("\n\n\n\t\t\t\t\t\tCONSTANT TABLE\n\t\t\t\t\t\t=============\n");
  printf("\n\t\t\t\tToken\t\t\t\tToken Type\t\t\t\tLine Number\n");
  for(int i=0;i<n_buckets;i++)
  {
      if(c_head[i]!=NULL)
      {
        struct table_entry *temp = c_head[i];
        while(temp!=NULL)
        {
          printf("\n\t\t\t\t%s\t\t\t\t<%s>\t\t\t\t%d", (char *)temp->key, (char *)temp->value, temp->line);
          temp = temp->next;
        }
      }
  }
  printf("\n");
}


int main()
{
  FILE *fp;
  fp = fopen("sample.c", "r");
  yyin = fp;
  printf("\n===========================================================================================================================================================");
  printf("\n\t\t\tTOKEN\t\t\t\tTOKEN TYPE\t\t\t\tLINE NUMBER");
  printf("\n===========================================================================================================================================================");
  int newtoken = 1;
  while(newtoken){
	newtoken = yylex();
  }
  print_symbol_table();
  print_constant_table();
  return 0;
}
int yywrap()
{
return 1;
}

