%token IDENTIFIER CONSTANT STRING_LITERAL 
%token CASE DEFAULT IF ELSE SWITCH WHILE DO FOR GOTO CONTINUE BREAK RETURN VOLATILE VOID UNSIGNED UNION TYPEDEF 
%token SWITCH STRUCT STATIC SIZEOF SIGNED SHORT RETURN REGISTER LONG INT FLOAT EXTERN ENUM DOUBLE CONST CHAR AUTO 
%token PTR_OP INC_OP DEC_OP LESS_OP GREAT_OP LE_OP GE_OP EQ_OP NE_OP
%token AND_OP OR_OP XOR_OP MUL_OP DIV_OP ADD_OP SUB_OP MOD_OP
%token MUL_ASSIGN DIV_ASSIGN MOD_ASSIGN ADD_ASSIGN
%token SUB_ASSIGN AND_ASSIGN
%token XOR_ASSIGN OR_ASSIGN
